// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: kubernetes
:page-layout: guide
:page-duration: 30 minutes
// :page-releasedate: 2018-03-16
:page-description: Explore how to deploy microservices to Kubernetes using Helm charts, setup an Ingress, and automatically rollout updates.
:page-tags: ['microservices']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Deploying microservices to Kubernetes

Explore how to deploy microservices to Kubernetes using Helm charts, setup an Ingress, and automatically rollout updates.

:minikube-ip: 192.168.99.100


== What you'll learn

You will learn how to deploy two microservices to a local Kubernetes cluster using Helm charts. This
will include building and containerizing the microservices, running the containers inside Kubernetes pods,
setting up an ingress to load balance traffic and persists sessions, establishing communicating
between the microservices, scaling deployments, and automatically rolling out new updates when the
microservices are rebuilt.

The two microservices you will deploy are called `name` and `ping` and are provided for you under the
`start/src` directory. The `name` microservice simply displays a brief greeting and the name of the
container that it runs in. This makes it easy to distinguish one running instance of this microservices
from another when its containerized and replicated. The `ping` microservice simply "pings" the Kubernetes
service that encapsulates the pods running the `name` microservice. This demonstrates how communication
between microservices can be established inside of a cluster.

You will use Minikube as your local Kubernetes cluster and the Helm package manager for Kubernetes to
deploy the two microservices. You will also use NGINX as your ingress controller, which you will enable
as an addon in Minikube.


// =================================================================================================
// What is Kubernetes
// =================================================================================================

== What is Kubernetes?

Kubernetes is an open-source container orchestrator that automates many tasks involved in deploying,
managing, and scaling containerized applications.

=== Architecture

A typical Kubernetes cluster is a collection of physical or virtual machines called `nodes`. A
cluster is made up of one master `node`, which manages the cluster, and multiple worker `nodes`,
which run the actual application instances inside Kuberntes objects called `pods`.

A `Pod` is a basic building block in a Kubernets cluster. It represents a single running process which
encapsulates an application container or in some scenarios multiple closely-coupled containers. `Pods`
can be replicated to scale applications and handle more traffic. A single `pod` or a group of replicated
`pods` are managed by Kubernetes objects called `controllers`. A `controller` handles replication,
self-healing, rollout of updates, and general management of `pods`. Some examples of `controllers`
are: `Deployment`, `StatefulSet`, and `DaemonSet`. In this guide, you will work with `deployments`.

A `pod` or a group of replicated `pods` are further grouped inside Kubernetes objects called `services`,
which define a set of rules by which the `pods` can be accessed. In a basic scenario, a Kubernetes
`service` will expose a node port, which can be used together with the cluster IP address to access
the `pods` encapsulated by the `service`. In this guide however, you will set up an `ingress`, which is
a Kubernetes object that maps external requests to the services in a cluster, as well as provides
additional functionality.

=== Why use Kubernetes?




// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

Before you begin, make sure have the following tools installed:

- `kubernetes-cli` - a command line interface for Kubernetes called `kubectl`. This is your primary
tool for communicating with and managing your Kubernetes cluster.
- `kubernetes-helm` - a package manager for Kubernetes called Helm. Helm allows you to install packages
or "charts", which are sets of preconfigured Kubernetes resources. Installing charts is much more
convenient as they can provide a lot of preconfigured functionality out of the box that normally needs
to be created manually.
- `minikube` - a local virtual machine that runs a single node Kubernetes cluster.

Finally, you will need a containerization software for building containers. Kubernetes supports a variety
of container types and while you're not limited to any of them in particular, this guide will focus
around Docker.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.


// =================================================================================================
// Staring and preparing your cluster for deployment
// =================================================================================================

== Starting and preparing your cluster for deployment

To begin working with your Minikube cluster run the following command from the command line:

```
minikube start
```

This command will setup and start your cluster. Minikube will also configure the cluster so it will
be ready to run out of the box. When you need to stop your cluster, run `minikube stop`.

Next, run the following command to initialize Helm to begin installing charts:

```
helm init
```

This command installs `Tiller` into your cluster which manages installations of your charts.

Next, add the IBM Helm chart repository:

```
helm repo add ibm-charts https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
```

This will give you access to a variety of IBM charts, including the Open Liberty chart, which you
will use to run the `name` and `ping` microservices.

Finally, run the following command to configure the Docker CLI to use the Minikube Docker daemon.
By doing this, you will be able to build Docker images directly to Minikube from your host machine:

```
eval $(minikube docker-env)
```

When you no longer wish to use the Minikube Docker daemon, run `eval $(minikube docker-env -u)` to
point back to your host.


// =================================================================================================
// Building and containerizing the microservices
// =================================================================================================

== Building and containerizing the microservices

The first step of deploying to Kubernetes is to build your microservices and containerize them with Docker.

The starting Java project, which you can find under the `start` directory, is a multi-module Maven
project thats made up of the `name` and `ping` microservices, each residing in their own directory.
Each of these directories contains a Dockerfile, which is picked up by the `dockerfile-maven` plugin
defined in the parent POM file. This enables you to build and containerize the microservices simultaneously
through Maven. To do this, run the Maven `package` goal from the command line:

```
cd start
mvn package
```

The `package` goal will automatically invoke the `dockerfile-maven:build` goal which builds a Docker
image from the Dockerfile located in the same directory as the POM file.

If the build runs successfully, you'll see various Docker messages describing what images are being
downloaded and built. Once the build is finished, run `docker images` from the command line to list
all images that are currently stored in the Docker cache. Verify that the `name:1.0-SNAPSHOT` and
`ping:1.0-SNAPSHOT` images are listed in the Minikube Docker cache:

[source, role="no_copy"]
----
$ docker images
REPOSITORY                                                       TAG
ping                                                             1.0-SNAPSHOT
name                                                             1.0-SNAPSHOT
open-liberty                                                     latest
gcr.io/kubernetes-helm/tiller                                    v2.9.0
k8s.gcr.io/kube-proxy-amd64                                      v1.10.0
k8s.gcr.io/kube-controller-manager-amd64                         v1.10.0
k8s.gcr.io/kube-apiserver-amd64                                  v1.10.0
k8s.gcr.io/kube-scheduler-amd64                                  v1.10.0
quay.io/kubernetes-ingress-controller/nginx-ingress-controller   0.12.0
k8s.gcr.io/etcd-amd64                                            3.1.12
k8s.gcr.io/kube-addon-manager                                    v8.6
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64                           1.14.8
k8s.gcr.io/k8s-dns-sidecar-amd64                                 1.14.8
k8s.gcr.io/k8s-dns-kube-dns-amd64                                1.14.8
k8s.gcr.io/pause-amd64                                           3.1
k8s.gcr.io/kubernetes-dashboard-amd64                            v1.8.1
k8s.gcr.io/kube-addon-manager                                    v6.5
gcr.io/k8s-minikube/storage-provisioner                          v1.8.0
gcr.io/k8s-minikube/storage-provisioner                          v1.8.1
k8s.gcr.io/defaultbackend                                        1.4
k8s.gcr.io/k8s-dns-sidecar-amd64                                 1.14.4
k8s.gcr.io/k8s-dns-kube-dns-amd64                                1.14.4
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64                           1.14.4
k8s.gcr.io/etcd-amd64                                            3.0.17
k8s.gcr.io/pause-amd64                                           3.0
----

If you don't see your images or if they've been built to your local Docker cache rather than Minikube's,
then check the Maven build log for any potential errors and make sure that your Docker CLI is configured
to use Minikube's Docker daemon rather than your host's.


// =================================================================================================
// Installing a Helm chart release
// =================================================================================================

== Installing a Helm chart release

Now that your Docker iamges are built, deploy them using the Open Liberty helm chart.

First, the `name` microservice:

```
helm install --name ol-name --set image.pullPolicy=IfNotPresent --set image.repository=name --set image.tag=1.0-SNAPSHOT --set ssl.enabled=false --set service.port=9080 --set service.targetPort=9080 --set ingress.enabled=true --set ingress.secureBackends=false --set ingress.rewriteTarget=/api/name --set ingress.path=/name ibm-charts/ibm-open-liberty
```

Then the `ping` microservice:

```
helm install --name ol-ping --set image.pullPolicy=IfNotPresent --set image.repository=ping --set image.tag=1.0-SNAPSHOT --set ssl.enabled=false --set service.port=9080 --set service.targetPort=9080 --set ingress.enabled=true --set ingress.secureBackends=false --set ingress.rewriteTarget=/api/ping --set ingress.path=/ping ibm-charts/ibm-open-liberty
```

There is quite bit going on here, so let's break down the parameters.


[cols="15, 15, 100", options="header"]
|===
| *Qualifier* | *Argument*     | *Description*
| image       | pullPolicy     | Image pull policy. In this case, you're using `IfNotPresent` for both
                                 microservices to have Kubelet pick up the local `name` and `ping`
                                 images rather than attempting to pull them from the public registry.
|             | repository     | Image name.
|             | tag            | Image tag. In this case, you're using `1.0-SNAPSHOT` for both microservices
                                 as its the project version defined in Maven.
| ssl         | enable         | Specifies whether to use SSL. In this case, you're disabling it since
                                 both of your microservice are not secured. As a result, you are also
                                 using `9080` as both service ports.
| service     | port           | The port exposed by the container.
|             | targetPort     | The port that will be exposed externally by the pod.
| ingress     | enable         | Specifies whether to use Ingress. An Ingress is a collection of rules
                                 that enable inbound requests to reach the cluster services.
|             | secureBackends | Tells NGINX which protocol it should use to reach the backend services.
                                 HTTPS if set to `true` and HTTP otherwise. In this case, since your
                                 services are not secured, you're using plain HTTP.
|             | rewriteTarget  | The endpoint where the traffic will be redirected. In this case, you're
                                 using the endpoints where your microservices are served.
|             | path           | A path where the Ingress will map to a particular backend service.
|===

In addition, the `--name` flag is used to specify a release name for the chart.

If you need to use additional parameters, visit the official IBM chart https://github.ibm.com/IBMPrivateCloud/charts/tree/master/stable/ibm-open-liberty[GitHub repository] for a complete list.

Once both charts are installed, run the `kubectl get pods` command to check on the status of your pods:

[source, role="no_copy"]
----
$ kubectl get pods
NAME                                        READY     STATUS    RESTARTS   AGE
ol-name-ibm-open-liberty-84fcb9475d-mgzjk   1/1       Running   0          55m
ol-ping-ibm-open-liberty-6cb6ffd7b6-5pp7w   1/1       Running   0          4m
----

You can also inspect the pods in more detail by running the `kubectl describe pods` command:

[source, role="no_copy"]
----
$ kubectl describe pods
Name:           ol-name-ibm-open-liberty-84fcb9475d-mgzjk
Namespace:      default
Node:           minikube/10.0.2.15
Start Time:     Tue, 22 May 2018 11:15:56 -0400
Labels:         app=ol-name-ibm-open-liberty
                pod-template-hash=4097650318
Annotations:    <none>
Status:         Running
IP:             172.17.0.7
Controlled By:  ReplicaSet/ol-name-ibm-open-liberty-84fcb9475d
Containers:
  ibm-open-liberty:
    Container ID:   docker://fcf2bddf4640931a5c0d378f5d85d1fb1fd3b74982fecbda3267cd17d40576b6
    Image:          name:1.0-SNAPSHOT
    Image ID:       docker://sha256:71ff030f9e47db7b4513289e223fcf55e856e8b6f7e5c634e5249c5a05683016
    Port:           <none>
    Host Port:      <none>
    State:          Running
...
----

The `get` and `describe` commands can also be invoked on other resources, such as `services`, `deployments`,
and `ingresses`. Feel free to use them to inspect all other resources created by the chart.

Alternatively to using `kubectl`, you can inspect your cluster directly from the Kubernetes dashboard
by running the `minikube dashboard` command.

Once your pods are up and running, run the `minikube ip` command to get the IP address of your Minikube cluster.
It will be {minikube-ip} by default. Then `curl` or visit the following URLs to access your microservices:

- https://{minikube-ip}/name/
- https://{minikube-ip}/ping/ol-name-ibm-open-liberty

The first URL will return a brief greeting following by the name of the pod that the `name`
microservice runs in. The second URL will return `pong` if it received a good response from the
`ol-name-ibm-open-liberty` Kubernetes `service`, which wraps the pod running the `name` microservice.
Visiting https://{minikube-ip}/ping/{kube-service} in general will return either a good or bad response
depending on whether the `kube-service` Kubernetes service is existent and accessible.


=== Breakdown of what is happening

how ingress is working, what happens if we dont use the ignress, explanation of the ports, etc.

deleting pods and self-healing, etc.


// =================================================================================================
// Scaling
// =================================================================================================

== Scaling

```
kubectl scale deployment ol-name-ibm-open-liberty --replicas=3
```

// =================================================================================================
// Rolling out updates
// =================================================================================================

== Rolling out updates

```
mvn versions:set -DnewVersion=1.1-SNAPSHOT
mvn clean package
```

If you dont create a new tag, then manually delete the pods to force them to respin and pickup the new image version:
```
kubectl delete pods -l app=ol-name-ibm-open-liberty
```

Otherwise, update with:

```
kubectl set image deployment/ol-name-ibm-open-liberty ibm-open-liberty=name:1.0-SNAPSHOT --record
```

=== Automating with Maven

```
mvn clean package -P update-deployment
```


// Include this section if appropriate
== Running the tests

// Include this for info on how to run the tests
include::{common-includes}/mvnverify.adoc[]

// Including a listing block with test results here

// OPTIONAL: after listing the test results, mention a simple change a user can make/introduce that
// will cause the tests to fail. Be brief and don't give the users all of the instructions. At this
// point, they should be comfortable enough to figure it out on their own.


== Great work! You're done!

// Briefly summarize what the user achieved in this guide (1-2 sentences).

// OPTIONAL: briefly state what the user could do next now that they've learned the technologies in this guide.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
