apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  # tag::labels1[]
  labels:
  # end::labels1[]
    # tag::app1[]
    app: system
    # end::app1[]
spec:
  selector:
    matchLabels:
      # tag::app2[]
      app: system
      # end::app2[]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      # tag::labels2[]
      labels:
      # end::labels2[]
        # tag::app3[]
        app: system
        # end::app3[]
    spec:
      containers:
      - name: system-container
        # tag::image1[]
        image: system:1.0-SNAPSHOT
        # end::image1[]
        ports:
        # tag::containerPort1[]
        - containerPort: 9080
        # end::containerPort1[]
        # system probes
        startupProbe:
          httpGet:
            # tag::start1[]
            path: /health/started
            # end::start1[]
            port: 9080
        livenessProbe:
          httpGet:
            # tag::live1[]
            path: /health/live
            # end::live1[]
            port: 9080
          # tag::delay1[]
          initialDelaySeconds: 60
          # end::delay1[]
          # tag::period1[]
          periodSeconds: 10
          # end::period1[]
          # tag::timeout1[]
          timeoutSeconds: 3
          # end::timeout1[]
          # tag::threshold1[]
          failureThreshold: 1
          # end::threshold1[]
        readinessProbe:
          httpGet:
            # tag::ready1[]
            path: /health/ready
            # end::ready1[]
            port: 9080
          # tag::delay2[]
          initialDelaySeconds: 30
          # end::delay2[]
          # tag::period2[]
          periodSeconds: 10
          # end::period2[]
          # tag::timeout2[]
          timeoutSeconds: 3
          # end::timeout2[]
          # tag::threshold2[]
          failureThreshold: 1
          # end::threshold2[]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  # tag::labels3[]
  labels:
  # end::labels3[]
    # tag::app4[]
    app: inventory
    # end::app4[]
spec:
  selector:
    matchLabels:
      # tag::app5[]
      app: inventory
      # end::app5[]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
  template:
    metadata:
      # tag::labels4[]
      labels:
      # end::labels4[]
        # tag::app6[]
        app: inventory
        # end::app6[]
    spec:
      containers:
      - name: inventory-container
        # tag::image2[]
        image: inventory:1.0-SNAPSHOT
        # end::image2[]
        ports:
        # tag::containerPort2[]
        - containerPort: 9080
        # end::containerPort2[]
         # inventory probes
        startupProbe:
          httpGet:
            # tag::start2[]
            path: /health/started
            # end::start2[]
            port: 9080
        livenessProbe:
          httpGet:
            # tag::live2[]
            path: /health/live
            # end::live2[]
            port: 9080
          # tag::delay3[]
          initialDelaySeconds: 60
          # end::delay3[]
          # tag::period3[]
          periodSeconds: 10
          # end::period3[]
          # tag::timeout3[]
          timeoutSeconds: 3
          # end::timeout3[]
          # tag::threshold3[]
          failureThreshold: 1
          # end::threshold3[]
        readinessProbe:
          httpGet:
            # tag::ready2[]
            path: /health/ready
            # end::ready2[]
            port: 9080
          # tag::delay4[]
          initialDelaySeconds: 30
          # end::delay4[]
          # tag::period4[]
          periodSeconds: 10
          # end::period4[]
          # tag::timeout4[]
          timeoutSeconds: 3
          # end::timeout4[]
          # tag::threshold4[]
          failureThreshold: 1
          # end::threshold4[]
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  # tag::NodePort1[]
  type: NodePort
  # end::NodePort1[]
  selector:
    # tag::app7[]
    app: system
    # end::app7[]
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    # tag::nodePort1[]
    nodePort: 31000
    # end::nodePort1[]

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  # tag::NodePort2[]
  type: NodePort
  # end::NodePort2[]
  selector:
    # tag::app8[]
    app: inventory
    # end::app8[]
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    # tag::nodePort2[]
    nodePort: 32000
    # end::nodePort2[]
